services:
  ###> doctrine/doctrine-bundle ###
  pager_database:
    image: mysql:8.0.27
    container_name: pager_database
    restart: always
    environment:
      MYSQL_DATABASE: 'pager'
      MYSQL_USER: 'pager'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    networks:
      - internal

  pager_nginx:
    image: nginx:latest
    container_name: pager_nginx
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=pager.zabtech.ru
      - NGINX_PORT=80
    networks:
      - internal

  pager_app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: pager_app
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    networks:
      - internal
    command:
      - "php-fpm"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - internal

volumes:
  my-db:

networks:
  internal:
    driver: bridge